### PR TITLE
add support for has_many through

### PR DESCRIPTION
**Pull request by drujensen**
This addresses #59 and adds the ability to access a many-to-many relationship using a `through` option to the `has_many` macro.

### CODE REVIEW

**Comment by drujensen** [comment]
@migeorge I added tests for pg and sqlite.

**Comment by drujensen** [comment]
@elorest After several comments and feedback, it's clear that we need to provide at least `belongs_to` and `has_many`.   I wanted to draw a line at DSL for SQL, but I can see why the slippery slope happens.  The abstraction is natural since you can remove the complexity of some queries with a convenience method.  Having a `has_many :users` is much cleaner than `def users ....join query... end`.

I'm not sure where to draw the line but probably with DSL that tries to generate SQL clause.
```
post.all("WHERE users.age = ?", 10)
```
vs
```
post.where(:age == 10)
```
or variant DSL.

**Comment by eliasjpr** [comment]
BTW I am all for named parameters ':age' vs position params `?`

**Comment by drujensen** [comment]
@eliasjpr yeah, that would be nice.  We might be able to abstract the differences from the drivers.  

@c910335 recently encapsulated the difference of the postgres using positional parameters `$1, $2, ...` to use '?' instead.  It actually supports both, which is nice.  

Adding support for named parameters for all the drivers would be really nice.

**Comment by c910335** [comment]
That was @migeorge's contribution, not mine.

**Pull request merged**
