### PR TITLE
UUID

### PR DESCRIPTION
**Pull request by wontruefree**
reopeing PR #102.  This has been rebased and conflicts resolved.

### CODE REVIEW

**Comment by wontruefree** [comment]
I am adding tests for associations but travis gets diffrent results then my local setup.

**Comment by drujensen** [comment]
@wontruefree Take a look at #166 Supporting Natural Keys.  I would like to use that approach for UUID support.  Let me know if that will support your use case.  If so, I would like to close this in favor of that.

**Comment by wontruefree** [comment]
@drujensen thanks for the update I will check it out.  I got stuck on associatons and ran out of time to work on this.

**Comment by faustinoaq** [comment]
> with the latest release, you can now specify the primary uuid : String, auto: false and then add a before_create hook to generate the uuid. I am going to close this PR. Let me know if the solution doesn't work for you and we can reopen.

@drujensen I think we can add a test for that, WDYT?

**Comment by drujensen** [comment]
yes, we could do that and use it as an example when others ask how to perform UUID.

**Pull request closed without merging**
